### ISSUE TITLE
富文本编辑器不能上传图片及附件

### ISSUE THREAD

**Issue by lzh-boy** [337547038/vue-form-design#3]
富文本编辑器不能设置上传图片及附件的配置

**Comment by 337547038** [comment]
上传需要配好接口地址才行，示例是不支持上传的

**Comment by lzh-boy** [comment]
![image](https://user-images.githubusercontent.com/2944129/161176441-2793d984-42bb-4b09-86fd-f2a39a51967a.png)
我指的是控件配置里面，没有上传路径及参数的配置项

**Comment by 337547038** [comment]
> ![image](https://user-images.githubusercontent.com/2944129/161176441-2793d984-42bb-4b09-86fd-f2a39a51967a.png) 我指的是控件配置里面，没有上传路径及参数的配置项

这种一般都是全局配置的吧，很少会说表单A的编辑器上传一个配置，表单B又一个配置的
